hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d-%H-%M-%S}
  job:
    chdir: True

size: 50
num_epochs: 1_000
num_parallell: 2
print_num: 25

epoch:
  num_parents: 24
  new_clustered: 4
  new_random: 4
  n_destroys: 1
  repair_function: greedy # unused
  n_children: 34
  mate_elite_prob_factor: 4.0