hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d-%H-%M-%S}
  job:
    chdir: True

size: 60
num_epochs: 1_500
num_parallell: 2
print_num: 25

epoch:
  num_parents: 30
  new_clustered: 4
  new_random: 4
  n_destroys: 1
  repair_function: greedy # unused
  n_children: 50
  mate_elite_prob_factor: 5.0